<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'TccSkippableSegment\Module'                           => __DIR__ . '/Module.php',
    'TccSkippableSegment\Mvc\Router\Http\SkippableSegment' => __DIR__ . '/src/TccSkippableSegment/Mvc/Router/Http/SkippableSegment.php',
);
